trigger:
- main

strategy:
  matrix:
    linux:
      operatingSystem: 'ubuntu-latest'
    mac:
      operatingSystem: 'macos-latest'  

pool:
  vmImage: $(operatingSystem)

steps:
- script: echo 'System Directory'+ $(operatingSystem)+ $(System.DefaultWorkingDirectory) 
  displayName: 'Display System Directory'
- script: echo 'SourcesDirectory Directory'+ $(operatingSystem)+ $(Build.SourcesDirectory)
  displayName: 'Display SourcesDirectory Directory'  
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: |
      **/*.yaml
      **/*.tf
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  
