trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo System Directory $(System.DefaultWorkingDirectory)
  displayName: 'Display System Directory'
- script: echo Artifact Directory $(Build.ArtifactStagingDirectory)
  displayName: 'Display Artifact Staging Directory'  
- script: echo Source Directory $(System.SourceDirectory)
  displayName: 'Display Source Directory'    
