trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo $(System.DefaultWorkingDirectory)
  displayName: 'Display System Directory'
- script: echo $(Build.ArtifactStagingDirectory)
  displayName: 'Display Staging Directory'  
