trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo System Directory $(System.DefaultWorkingDirectory)
  displayName: 'Display System Directory'
- script: echo SourcesDirectory Directory $(Build.SourcesDirectory)
  displayName: 'Display SourcesDirectory Directory'  
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DafaultWorkingDirectory)'
    Contents: |
      **/*.yaml
      **/*.tf
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  
